name: Destroy Infrastructure
on:
  workflow_dispatch:  # Makes this workflow manually triggerable from GitHub UI

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20    # Updated to Node.js 20
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Install CDK CLI
        run: npm install -g aws-cdk
        
      - name: Install CDK dependencies
        working-directory: cdk
        run: npm install
      
      - name: Destroy Infrastructure
        working-directory: cdk
        run: |
          # Empty the ECR repository first
          REPO_URI="444515292128.dkr.ecr.us-east-1.amazonaws.com/prod-app-repository"
          aws ecr list-images --repository-name prod-app-repository --query 'imageIds[*]' --output json | \
          jq -r '.[] | .imageDigest' | \
          while read digest; do
            aws ecr batch-delete-image --repository-name prod-app-repository --image-ids imageDigest=$digest
          done

          # Now destroy the CDK stack
          cdk destroy --force --all